version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "15432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  symmioeventsdb:
    build: .
    depends_on:
      - db
    environment:
      RPC_URL: "https://0xrpc.io/base"
      CONTRACT_ADDRESS: "0x91Cf2D8Ed503EC52768999aA6D8DBeA6e52dbe43"
      ABI_DIR: "/app/abi"
      START_BLOCK: "33068760"
      FINALITY_BLOCK: "2"
      PG_HOST: "db"
      PG_PORT: "5432"
      PG_USER: "postgres"
      PG_PASSWORD: "postgres"
      PG_DBNAME: "postgres"
      MAX_RETRIES: "100"
      MAX_BLOCK_RANGE: "10000"
      RETRY_DELAY_SECONDS: "5"
      ENABLE_GORM_LOGS: "false"
    # Uncomment if you want to see logs in the foreground
    # tty: true
    # stdin_open: true

volumes:
  db_data: